### PR TITLE
Allow Currency variants to be sorted lexicographically

### PR DESCRIPTION
**Pull request by jmagnusson**
Useful when the currency is a field in a struct and the struct needs to implement `PartialOrd` and/or `Ord`.

### CODE REVIEW

**Comment by zbrox** [comment]
Thanks for contributing! I tried to use the GitHub editor to resolve the conflicts cause I'm not behind a computer to do it properly and I guess I didn't do so well cause it still won't let me merge. I will take a look tomorrow maybe to try to resolve this. Sorry for the delay.

**Comment by jmagnusson** [comment]
My pleasure, thanks for a great lib! Take your time, Cargo makes it easy to use a custom version 😀

**Comment by zbrox** [comment]
When I get behind a computer I will merge this and will release a 0.4.2

**Comment by zbrox** [comment]
@jmagnusson `0.4.2` is published.

**Comment by jmagnusson** [comment]
Great, thanks @zbrox 👍

**Comment by zbrox** [comment]
@jmagnusson if you have any more ideas to improve this I'm all ears. I haven't used the library for a while, so I'm not sure what else would be useful in a real world use case.

**Comment by jmagnusson** [comment]
One thing I could think of is setting up a weekly/monthly cronjob to fetch the latest currency data and then automatically creating a pull request on any changes via release-please or the likes of it.

**Comment by zbrox** [comment]
Yeah, I had something for that but it was kinda prone to breaking. I can try to unbury the script wherever it is right now and put it in a GitHub Action and see if I can make it more reliable. The big problem there is that not all the data is available in one place, e.g. the subunit symbols. But it's definitely something that should be automated somehow.

**Comment by jmagnusson** [comment]
Sounds good. What’s the source of the data? Might take a stab at it one day if I get some spare time.

**Comment by zbrox** [comment]
The bulk of the data is from https://en.wikipedia.org/wiki/ISO_4217 but then it's crawling the articles for each individual currency for symbols, country codes, subunit fractions and subunit symbols.

**Comment by zbrox** [comment]
Thinking about another difficulty now, which is manual edits of the data which are sometimes necessary if the data is missing on Wikipedia or is just a bit innacurate.

**Comment by jmagnusson** [comment]
Huh. I just assumed that you got a complete dataset from somewhere. If it’s all from Wikipedia then we could perhaps correct any erroneous entries there?

**Comment by zbrox** [comment]
I couldn't find an open dataset that covers this info. So some of the info I resorted to semi-manual gathering. And it completely skipped my mind that any missing info can still be (and should be?) added to Wikipedia :)

**Pull request merged**
